spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres/potal_db
spring.datasource.username=mango
spring.datasource.password=Qkrrudghks!1!

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true