create table if not exists post_reactions (
    reaction_id bigint generated by default as identity primary key,
    post_id bigint not null references posts(post_id) on delete cascade,
    user_id bigint not null references users(user_id) on delete cascade,
    reaction_type varchar(20) not null,
    created_at timestamp with time zone not null default now(),
    constraint uk_post_reactions_post_user unique (post_id, user_id),
    constraint ck_post_reactions_type check (reaction_type in ('RECOMMEND', 'DISLIKE'))
);

create index if not exists idx_post_reactions_user_id
    on post_reactions(user_id);
